"""add role to user

Revision ID: 5605b685eaa1
Revises: a4f2d9c8e1b3
Create Date: 2026-04-27 22:06:23.796005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5605b685eaa1'
down_revision: Union[str, Sequence[str], None] = 'a4f2d9c8e1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_trx_id'), table_name='payments')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_index(op.f('ix_payments_trx_id'), 'payments', ['trx_id'], unique=True)
    # ### end Alembic commands ###
